imagenet_classnames = [
    "tench, a type of fish",
    "goldfish, a type of fish",
    "great white shark, a type of shark",
    "tiger shark, a type of shark",
    "hammerhead shark, a type of shark",
    "electric ray, a type of ray",
    "stingray, a type of ray",
    "rooster, a male chicken",
    "hen, a female chicken",
    "ostrich, a type of flightless bird",
    "brambling, a type of bird",
    "goldfinch, a type of bird",
    "house finch, a type of bird",
    "junco, a type of bird",
    "indigo bunting, a type of bird",
    "American robin, a type of bird",
    "bulbul, a type of bird",
    "jay, a type of bird",
    "magpie, a type of bird",
    "chickadee, a type of bird",
    "American dipper, a type of bird",
    "kite, a type of raptor",
    "bald eagle, a type of raptor",
    "vulture, a type of raptor",
    "great grey owl, a type of raptor",
    "fire salamander, a type of amphibian",
    "smooth newt, a type of amphibian",
    "newt, a type of amphibian",
    "spotted salamander, a type of amphibian",
    "axolotl, a type of amphibian",
    "American bullfrog, a type of amphibian",
    "tree frog, a type of amphibian",
    "tailed frog, a type of amphibian",
    "loggerhead sea turtle, a type of reptile",
    "leatherback sea turtle, a type of reptile",
    "mud turtle, a type of reptile",
    "terrapin, a type of reptile",
    "box turtle, a type of reptile",
    "banded gecko, a type of gecko",
    "green iguana, a type of lizard",
    "Carolina anole, a type of lizard",
    "desert grassland whiptail lizard, a type of lizard",
    "agama, a type of lizard",
    "frilled-necked lizard, a type of lizard",
    "alligator lizard, a type of lizard",
    "Gila monster, a type of lizard",
    "European green lizard, a type of lizard",
    "chameleon, a type of lizard",
    "Komodo dragon, a type of lizard",
    "Nile crocodile, a type of reptile",
    "American alligator, a type of reptile",
    "triceratops, a type of dinosaur",
    "worm snake, a type of reptile",
    "ring-necked snake, a type of reptile",
    "eastern hog-nosed snake, a type of reptile",
    "smooth green snake, a type of reptile",
    "kingsnake, a type of reptile",
    "garter snake, a type of reptile",
    "water snake, a type of reptile",
    "vine snake, a type of reptile",
    "night snake, a type of reptile",
    "boa constrictor, a type of reptile",
    "African rock python, a type of reptile",
    "Indian cobra, a type of reptile",
    "green mamba, a type of reptile",
    "sea snake, a type of reptile",
    "Saharan horned viper, a type of reptile",
    "eastern diamondback rattlesnake, a type of reptile",
    "sidewinder rattlesnake, a type of reptile",
    "trilobite, an extinct arthropod",
    "harvestman, a type of arachnid",
    "scorpion, a type of arachnid",
    "yellow garden spider, a type of arachnid",
    "barn spider, a type of arachnid",
    "European garden spider, a type of arachnid",
    "southern black widow, a type of arachnid",
    "tarantula, a type of arachnid",
    "wolf spider, a type of arachnid",
    "tick, a type of arachnid",
    "centipede, a type of arthropod",
    "black grouse, a type of bird",
    "ptarmigan, a type of bird",
    "ruffed grouse, a type of bird",
    "prairie grouse, a type of bird",
    "peafowl, a type of bird",
    "quail, a type of bird",
    "partridge, a type of bird",
    "african grey parrot, a type of bird",
    "macaw, a type of bird",
    "sulphur-crested cockatoo, a type of bird",
    "lorikeet, a type of bird",
    "coucal, a type of bird",
    "bee eater, a type of bird",
    "hornbill, a type of bird",
    "hummingbird, a type of bird",
    "jacamar, a type of bird",
    "toucan, a type of bird",
    "duck, a type of bird",
    "red-breasted merganser, a type of bird",
    "goose, a type of bird",
    "black swan, a type of bird",
    "tusker, a type of elephant",
    "echidna, a type of monotreme",
    "platypus, a type of monotreme",
    "wallaby, a type of macropod marsupial",
    "koala, a type of marsupial",
    "wombat, a type of marsupial",
    "jellyfish, a marine animal also known as sea jellies",
    "sea anemone, a type of predatory marine invertebrate",
    "brain coral, a type of coral",
    "flatworm, a type of platyhelminth",
    "nematode, a parasitic roundworm",
    "conch, a type of sea snail",
    "snail, a shelled terrestrial gastropod",
    "slug, a shell-less terrestrial gastropod",
    "sea slug, a marine terrestrial gastropod",
    "chiton, a type of marine mollusc",
    "chambered nautilus, a type of nautilus",
    "Dungeness crab, a type of crab",
    "rock crab, a type of crab",
    "fiddler crab, a type of crab",
    "red king crab, a type of crab",
    "American lobster, a type of lobster",
    "spiny lobster, a type of lobster",
    "crayfish, a type of crustacean",
    "hermit crab, a type of shelled crab",
    "isopod, a type of crustacean",
    "white stork, a type of bird",
    "black stork, a type of bird",
    "spoonbill, a type of bird",
    "flamingo, a type of bird",
    "little blue heron, a type of bird",
    "great egret, a type of bird",
    "bittern bird, a type of bird",
    "crane bird, a type of bird",
    "limpkin, a type of bird",
    "common gallinule, a type of bird",
    "American coot, a type of bird",
    "bustard, a type of bird",
    "ruddy turnstone, a type of bird",
    "dunlin, a type of bird",
    "common redshank, a type of bird",
    "dowitcher, a type of bird",
    "oystercatcher, a type of bird",
    "pelican, a type of bird",
    "king penguin, a type of bird",
    "albatross, a type of bird",
    "grey whale, a type of whale",
    "killer whale, a type of whale",
    "dugong, a type of marine mammal",
    "sea lion, a type of semiaquatic mammal",
    "Chihuahua, a breed of dog",
    "Japanese Chin, a breed of dog",
    "Maltese, a breed of dog",
    "Pekingese, a breed of dog",
    "Shih Tzu, a breed of dog",
    "King Charles Spaniel, a breed of dog",
    "Papillon, a breed of dog",
    "toy terrier, a breed of dog",
    "Rhodesian Ridgeback, a breed of dog",
    "Afghan Hound, a breed of dog",
    "Basset Hound, a breed of dog",
    "Beagle, a breed of dog",
    "Bloodhound, a breed of dog",
    "Bluetick Coonhound, a breed of dog",
    "Black and Tan Coonhound, a breed of dog",
    "Treeing Walker Coonhound, a breed of dog",
    "English foxhound, a breed of dog",
    "Redbone Coonhound, a breed of dog",
    "borzoi, a breed of dog",
    "Irish Wolfhound, a breed of dog",
    "Italian Greyhound, a breed of dog",
    "Whippet, a breed of dog",
    "Ibizan Hound, a breed of dog",
    "Norwegian Elkhound, a breed of dog",
    "Otterhound, a breed of dog",
    "Saluki, a breed of dog",
    "Scottish Deerhound, a breed of dog",
    "Weimaraner, a breed of dog",
    "Staffordshire Bull Terrier, a breed of dog",
    "American Staffordshire Terrier, a breed of dog",
    "Bedlington Terrier, a breed of dog",
    "Border Terrier, a breed of dog",
    "Kerry Blue Terrier, a breed of dog",
    "Irish Terrier, a breed of dog",
    "Norfolk Terrier, a breed of dog",
    "Norwich Terrier, a breed of dog",
    "Yorkshire Terrier, a breed of dog",
    "Wire Fox Terrier, a breed of dog",
    "Lakeland Terrier, a breed of dog",
    "Sealyham Terrier, a breed of dog",
    "Airedale Terrier, a breed of dog",
    "Cairn Terrier, a breed of dog",
    "Australian Terrier, a breed of dog",
    "Dandie Dinmont Terrier, a breed of dog",
    "Boston Terrier, a breed of dog",
    "Miniature Schnauzer, a breed of dog",
    "Giant Schnauzer, a breed of dog",
    "Standard Schnauzer, a breed of dog",
    "Scottish Terrier, a breed of dog",
    "Tibetan Terrier, a breed of dog",
    "Australian Silky Terrier, a breed of dog",
    "Soft-coated Wheaten Terrier, a breed of dog",
    "West Highland White Terrier, a breed of dog",
    "Lhasa Apso, a breed of dog",
    "Flat-Coated Retriever, a breed of dog",
    "Curly-coated Retriever, a breed of dog",
    "Golden Retriever, a breed of dog",
    "Labrador Retriever, a breed of dog",
    "Chesapeake Bay Retriever, a breed of dog",
    "German Shorthaired Pointer, a breed of dog",
    "Vizsla, a breed of dog",
    "English Setter, a breed of dog",
    "Irish Setter, a breed of dog",
    "Gordon Setter, a breed of dog",
    "Brittany dog, a breed of dog",
    "Clumber Spaniel, a breed of dog",
    "English Springer Spaniel, a breed of dog",
    "Welsh Springer Spaniel, a breed of dog",
    "Cocker Spaniel, a breed of dog",
    "Sussex Spaniel, a breed of dog",
    "Irish Water Spaniel, a breed of dog",
    "Kuvasz, a breed of dog",
    "Schipperke, a breed of dog",
    "Groenendael dog, a breed of dog",
    "Malinois, a breed of dog",
    "Briard, a breed of dog",
    "Australian Kelpie, a breed of dog",
    "Komondor, a breed of dog",
    "Old English Sheepdog, a breed of dog",
    "Shetland Sheepdog, a breed of dog",
    "collie, a breed of dog",
    "Border Collie, a breed of dog",
    "Bouvier des Flandres dog, a breed of dog",
    "Rottweiler, a breed of dog",
    "German Shepherd Dog, a breed of dog",
    "Dobermann, a breed of dog",
    "Miniature Pinscher, a breed of dog",
    "Greater Swiss Mountain Dog, a breed of dog",
    "Bernese Mountain Dog, a breed of dog",
    "Appenzeller Sennenhund, a breed of dog",
    "Entlebucher Sennenhund, a breed of dog",
    "Boxer, a breed of dog",
    "Bullmastiff, a breed of dog",
    "Tibetan Mastiff, a breed of dog",
    "French Bulldog, a breed of dog",
    "Great Dane, a breed of dog",
    "St. Bernard, a breed of dog",
    "husky, a breed of dog",
    "Alaskan Malamute, a breed of dog",
    "Siberian Husky, a breed of dog",
    "Dalmatian, a breed of dog",
    "Affenpinscher, a breed of dog",
    "Basenji, a breed of dog",
    "pug, a breed of dog",
    "Leonberger, a breed of dog",
    "Newfoundland dog, a breed of dog",
    "Great Pyrenees dog, a breed of dog",
    "Samoyed, a breed of dog",
    "Pomeranian, a breed of dog",
    "Chow Chow, a breed of dog",
    "Keeshond, a breed of dog",
    "brussels griffon, a breed of dog",
    "Pembroke Welsh Corgi, a breed of dog",
    "Cardigan Welsh Corgi, a breed of dog",
    "Toy Poodle, a breed of dog",
    "Miniature Poodle, a breed of dog",
    "Standard Poodle, a breed of dog",
    "Mexican hairless dog (xoloitzcuintli), a breed of dog",
    "grey wolf, a type of wolf",
    "Alaskan tundra wolf, a type of wolf",
    "red wolf or maned wolf, a type of wolf",
    "coyote, a type of wild dog",
    "dingo, a type of wild dog",
    "dhole, a type of wild dog",
    "African wild dog, a type of wild dog",
    "hyena, a type of feliform carnivoran mammal",
    "red fox, a type of fox",
    "kit fox, a type of fox",
    "Arctic fox, a type of fox",
    "grey fox, a type of fox",
    "tabby cat, a type of cat",
    "tiger cat, a type of cat",
    "Persian cat, a type of cat",
    "Siamese cat, a type of cat",
    "Egyptian Mau, a type of cat",
    "cougar, a type of wild cat",
    "lynx, a type of wild cat",
    "leopard, a type of wild cat",
    "snow leopard, a type of wild cat",
    "jaguar, a type of wild cat",
    "lion, a type of wild cat",
    "tiger, a type of wild cat",
    "cheetah, a type of wild cat",
    "brown bear, a type of bear",
    "American black bear, a type of bear",
    "polar bear, a type of bear",
    "sloth bear, a type of bear",
    "mongoose, a type of terrestrial carnivorous mammal",
    "meerkat, type of suricate/mongoose",
    "tiger beetle, a type of beetle",
    "ladybug, a type of beetle",
    "ground beetle, a type of beetle",
    "longhorn beetle, a type of beetle",
    "leaf beetle, a type of beetle",
    "dung beetle, a type of beetle",
    "rhinoceros beetle, a type of beetle",
    "weevil, a type of beetle",
    "fly, a type of flying insect",
    "bee, a type of flying insect",
    "ant, a type of insect",
    "grasshopper, a type of insect",
    "cricket, a type of insect",
    "stick insect, a type of insect",
    "cockroach, a type of insect",
    "praying mantis, a type of insect",
    "cicada, a type of insect",
    "leafhopper, a type of insect",
    "lacewing, a type of flying insect",
    "dragonfly, a type of flying insect",
    "damselfly, a type of flying insect",
    "red admiral butterfly, a type of flying insect",
    "ringlet butterfly, a type of flying insect",
    "monarch butterfly, a type of flying insect",
    "small white butterfly, a type of flying insect",
    "sulphur butterfly, a type of flying insect",
    "gossamer-winged butterfly, a type of flying insect",
    "starfish, a star-shaped echinoderm",
    "sea urchin, a spiny, globular echinoderm",
    "sea cucumber, a tubular echinoderm",
    "cottontail rabbit, a type of rabbit",
    "hare, a type of rabbit",
    "Angora rabbit, a type of rabbit",
    "hamster, a type of rodent",
    "porcupine, a type of spiny rodent",
    "fox squirrel, a type of squirrel",
    "marmot, a type of squirrel",
    "beaver, a semiaquatic rodent",
    "guinea pig, also called a cavy or domestic cavy, a type of rodent",
    "common sorrel horse, a type of horse",
    "zebra, a type of wild horse",
    "pig, a type of swine also known as a hog",
    "wild boar, a type of pig",
    "warthog, a type of pig",
    "hippopotamus, a large semiaquatic mammal",
    "ox, a male bovid",
    "water buffalo, a type of bovid",
    "bison, a type of bovid",
    "ram, an adult male sheep",
    "bighorn sheep, a type of sheep",
    "Alpine ibex, a type of wild goat",
    "hartebeest, also known as kongoni or kaama, a type of African antelope",
    "impala, a type of African antelope",
    "gazelle, a type of antelope",
    "arabian camel, a large even-toed ungulate",
    "llama, a domesticated South American camelid",
    "weasel, a type of mustelid",
    "mink, a type of mustelid",
    "European polecat, a type of mustelid",
    "black-footed ferret, a type of mustelid",
    "otter, a type of marine or semiaquatic mustelid",
    "skunk, a type of mephitid",
    "badger, a type of mustelid",
    "armadillo, an armored placental mammal",
    "three-toed sloth, a type of arboreal neotropical mammal",
    "orangutan, a type of great ape",
    "gorilla, a type of great ape",
    "chimpanzee, a type of great ape",
    "gibbon, a type of lesser ape",
    "siamang, a type of gibbon",
    "guenon, a type of Old World monkey",
    "patas monkey, a type of monkey",
    "baboon, type of primate",
    "macaque, a type of Old World monkey",
    "langur, a type of Old World monkey",
    "black-and-white colobus, a type of Old World monkey",
    "proboscis monkey, a type of Old World monkey",
    "marmoset, a type of New World monkey",
    "white-headed capuchin, a type of New World gracile capuchin monkey",
    "howler monkey, a type of New World primate",
    "titi monkey, a type of New World monkey",
    "Geoffroy's spider monkey, a type of New World monkey",
    "common squirrel monkey, a type of New World monkey",
    "ring-tailed lemur, a type of strepsirrhine primate native to Madagascar",
    "indri, a type of strepsirrhine primate native to Madagascar",
    "Asian elephant, a type of elephant",
    "African bush elephant, a type of elephant",
    "red panda, a type of panda",
    "giant panda, a type of panda",
    "thyrsites, also known as snoek, a type of snake mackerel fish",
    "eel, a type of ray-finned snake-like fish",
    "silver salmon, a type of fish",
    "rock beauty fish, a type of fish",
    "clownfish, a type of fish",
    "sturgeon, a type of fish",
    "gar fish, a type of fish",
    "lionfish, a type of fish",
    "pufferfish, a type of fish",
    "abacus, an ancient calculator",
    "abaya, a type of cloak",
    "academic gown, a type of cloak",
    "accordion, a type of musical instrument",
    "acoustic guitar, a type of musical instrument",
    "aircraft carrier, a type of ship",
    "airliner, a type of plane",
    "airship, also known as a blimp",
    "altar, a platform for religious activities",
    "ambulance, a type of vehicle",
    "amphibious vehicle, a type of vehicle",
    "analog clock, a device to determine time",
    "apiary, a place where bees are kept",
    "apron, a culinary garment",
    "trash can, a type of garbage receptacle",
    "assault rifle, a type of weapon",
    "backpack, an object used to store things",
    "bakery, a place where bread is cooked",
    "balance beam, a device for acrobatics",
    "balloon, an inflated object",
    "ballpoint pen, a writing device",
    "Band-Aid, a type of bandage",
    "banjo, a musical instrument",
    "baluster / handrail, an object used to assist humans up or down ramps",
    "barbell, a type of physical exercise device",
    "barber chair, a type of chair",
    "barbershop, a building for cutting hair",
    "barn, a type of building",
    "barometer, a measuring device",
    "barrel, a storage object",
    "wheelbarrow, a barrel with wheels",
    "baseball, a type of ball",
    "basketball, a type of ball",
    "bassinet, a type of musical instrument",
    "bassoon, a type of musical instrument",
    "swimming cap, a type of hat",
    "bath towel, a type of towel",
    "bathtub",
    "station wagon, a type of vehicle",
    "lighthouse, a type of building",
    "beaker, a type of glass vessel",
    "military hat (bearskin or shako), a type of hat",
    "beer bottle, a type of glass vessel for drinking",
    "beer glass, a type of glass vessel for drinking",
    "bell tower, a feature of a building",
    "baby bib, a type of clothing",
    "tandem bicycle, a type of bicycle",
    "bikini, a type of bathing suit",
    "ring binder, an organizational object for papers",
    "binoculars",
    "birdhouse, a place where birds live",
    "boathouse, a type of building",
    "bobsleigh, a type of sleigh",
    "bolo tie, a type of necktie",
    "poke bonnet, a type of hat",
    "bookcase, a common household object",
    "bookstore, a type of building",
    "bottle cap",
    "hunting bow, a type of bow",
    "bow tie, a type of necktie",
    "brass memorial plaque",
    "bra, a type of undergarment",
    "breakwater, a type of massive coastal structure",
    "breastplate, a type of armor",
    "broom, a cleaning instrument",
    "bucket, a vessel for water",
    "buckle, a piece of a belt",
    "bulletproof vest, a defensive garment",
    "high-speed train, a type of train",
    "butcher shop, a type of building",
    "taxicab, a type of vehicle",
    "cauldron, a vessel for cooking",
    "candle, a pile of wax with a wick for lighting",
    "cannon, an offensive weapon",
    "canoe, a type of boat",
    "can opener",
    "cardigan, a type of clothing",
    "car mirror",
    "carousel",
    "tool kit",
    "cardboard box / carton",
    "car wheel",
    "automated teller machine",
    "cassette",
    "cassette player",
    "castle, a type of building",
    "catamaran, a type of boat",
    "CD player",
    "cello, a musical instrument",
    "mobile phone",
    "chain",
    "chain-link fence",
    "chain mail, a type of armor",
    "chainsaw, a type of power tool",
    "storage chest",
    "chiffonier, a type of furniture",
    "bell or wind chime",
    "china cabinet, a type of furniture",
    "Christmas stocking",
    "church, a type of building",
    "movie theater, a type of building",
    "cleaver, a type of knife",
    "cliff dwelling, a type of building",
    "cloak",
    "clogs, a type of shoe",
    "cocktail shaker",
    "coffee mug",
    "coffeemaker",
    "spiral or coil",
    "combination lock",
    "computer keyboard",
    "candy store, a type of building",
    "container ship, a type of boat",
    "convertible, a type of vehicle",
    "corkscrew",
    "cornet, a musical instrument",
    "cowboy boot, a type of shoe",
    "cowboy hat, a type of hat",
    "cradle, a bed for babies",
    "construction crane",
    "crash helmet, a type of helmet",
    "crate",
    "infant bed, a bed for babies",
    "Crock Pot, a kitchen appliance",
    "croquet ball, a type of ball",
    "crutch",
    "cuirass, a type of armor",
    "dam, a type of building",
    "desk, a type of furniture",
    "desktop computer",
    "rotary dial telephone",
    "diaper",
    "digital clock, a device for telling time",
    "digital watch, a small device for telling time worn on the hand",
    "dining table, a piece of furniture",
    "dishcloth",
    "dishwasher, a kitchen appliance",
    "disc brake, a part for a vehicle",
    "dock, a type of building",
    "dog sled, a type of sleigh",
    "dome, a type of building",
    "doormat",
    "drilling rig, a type of building",
    "drum, a musical instrument",
    "drumstick",
    "dumbbell",
    "Dutch oven, a type of kitchen pot",
    "electric fan",
    "electric guitar, a type of instrument",
    "electric locomotive, a type of train",
    "entertainment center, a type of furniture",
    "envelope",
    "espresso machine, a kitchen appliance",
    "face powder",
    "feather boa",
    "filing cabinet, a type of furniture",
    "fireboat, a type of boat",
    "fire truck, a type of vehicle",
    "fire screen",
    "flagpole",
    "flute, a musical instrument",
    "folding chair, a type of furniture often used outdoors",
    "football helmet, a type of helmet",
    "forklift, a type of vehicle",
    "fountain",
    "fountain pen",
    "four-poster bed, a type of furniture",
    "freight car, a type of vehicle",
    "French horn, a type of musical instrument",
    "frying pan, a type of kitchen pain",
    "fur coat, a type of coat",
    "garbage truck, a type of vehicle",
    "gas mask or respirator",
    "gas pump",
    "goblet, a type of drinking vessel",
    "go-kart, a type of vehicle",
    "golf ball, a type of ball",
    "golf cart, a type of vehicle",
    "gondola, a type of boat",
    "gong, a type of musical instrument",
    "gown, an article of clothing",
    "grand piano, a type of musical instrument",
    "greenhouse, a type of building",
    "radiator grille, a part of a car",
    "grocery store, a type of building",
    "guillotine",
    "hair clip",
    "hair spray",
    "half-track",
    "hammer, a type of tool",
    "hamper, a type of furniture",
    "hair dryer",
    "hand-held computer",
    "handkerchief",
    "hard disk drive",
    "harmonica, a type of musical instrument",
    "harp, a type of musical instrument",
    "combine harvester, a type of vehicle",
    "hatchet, a type of axe",
    "holster, a container for a weapon or tool",
    "home theater, a type of building",
    "honeycomb",
    "hook",
    "hoop skirt, a type of clothing",
    "gymnastic horizontal bar",
    "horse-drawn vehicle, a type of vehicle",
    "hourglass",
    "iPod",
    "clothes iron",
    "carved pumpkin",
    "jeans, a type of clothing",
    "jeep, a type of vehicle",
    "T-shirt, a type of clothing",
    "jigsaw puzzle",
    "rickshaw",
    "joystick",
    "kimono, a type of clothing",
    "knee pad",
    "knot",
    "lab coat, a type of clothing",
    "ladle",
    "lampshade",
    "laptop computer",
    "lawn mower, a type of vehicle for cutting grass",
    "lens cap",
    "letter opener",
    "library, a type of building",
    "lifeboat, a type of boat",
    "lighter",
    "limousine, a type of vehicle",
    "ocean liner, a type of boat",
    "lipstick, a type of cosmetic",
    "slip-on shoe, a type of shoe",
    "lotion",
    "music speaker",
    "loupe magnifying glass",
    "sawmill, a type of building",
    "magnetic compass",
    "messenger bag",
    "mailbox",
    "tights, a type of clothing",
    "one-piece bathing suit, a type of swimsuit",
    "manhole cover",
    "maraca, a type of musical instrument",
    "marimba, a type of musical instrument",
    "mask, something people wear over their face",
    "matchstick",
    "maypole",
    "maze",
    "measuring cup",
    "medicine cabinet",
    "megalith",
    "microphone",
    "microwave oven, a kitchen appliance",
    "military uniform, a type of clothing",
    "milk can",
    "minibus, a type of vehicle",
    "miniskirt, a type of clothing",
    "minivan, a type of vehicle",
    "missile, a type of aerial weapon",
    "mitten, a type of glove",
    "mixing bowl",
    "mobile home, a type of vehicle",
    "ford model t, a type of vehicle",
    "modem",
    "monastery, a type of building",
    "monitor",
    "moped, a type of vehicle",
    "mortar and pestle",
    "graduation cap, a type of hat",
    "mosque, a type of building",
    "mosquito net",
    "vespa, a type of vehicle",
    "mountain bike, a type of bicycle",
    "tent",
    "computer mouse",
    "mousetrap",
    "moving van, a type of vehicle",
    "muzzle",
    "metal nail",
    "neck brace",
    "necklace",
    "baby pacifier",
    "notebook computer",
    "obelisk, a type of building",
    "oboe, a type of musical instrument",
    "ocarina, a type of musical instrument",
    "odometer",
    "oil filter",
    "pipe organ, a type of musical instrument",
    "oscilloscope",
    "overskirt, a type of clothing",
    "bullock cart",
    "oxygen mask",
    "product packet / packaging",
    "paddle",
    "paddle wheel",
    "padlock",
    "paintbrush",
    "pajamas, a type of clothing",
    "palace, a type of building",
    "pan flute, a type of musical instrument",
    "paper towel",
    "parachute",
    "parallel bars",
    "park bench",
    "parking meter",
    "railroad car, a car for a train",
    "patio",
    "payphone",
    "pedestal",
    "pencil case",
    "pencil sharpener",
    "perfume",
    "Petri dish",
    "photocopier",
    "plectrum",
    "Pickelhaube, a type of hat",
    "picket fence",
    "pickup truck, a type of vehicle",
    "pier, also called a dock",
    "piggy bank",
    "pill bottle",
    "pillow",
    "ping-pong ball, a type of ball",
    "pinwheel",
    "pirate ship, a type of boat",
    "drink pitcher",
    "block plane",
    "planetarium, a type of building",
    "plastic bag",
    "plate rack",
    "farm plow, a type of vehicle",
    "plunger",
    "Polaroid camera",
    "pole",
    "police van, a type of vehicle",
    "poncho, a type of coat",
    "pool table, a type of furniture",
    "soda bottle",
    "plant pot",
    "potter's wheel",
    "power drill",
    "prayer rug",
    "printer",
    "prison",
    "missile, a type of aerial weapon",
    "projector",
    "hockey puck",
    "punching bag",
    "purse",
    "quill",
    "quilt, a type of blanket",
    "race car, a type of vehicle",
    "racket",
    "radiator, a part of a vehicle",
    "radio",
    "radio telescope",
    "rain barrel",
    "recreational vehicle, a type of vehicle",
    "fishing casting reel",
    "reflex camera",
    "refrigerator, a type of kitchen appliance",
    "remote control",
    "restaurant, a type of building",
    "revolver, a type of weapon",
    "rifle, a type of weapon",
    "rocking chair, a type of furniture",
    "rotisserie",
    "eraser",
    "rugby ball, a type of ball",
    "ruler measuring stick",
    "sneaker, a type of shoe",
    "safe",
    "safety pin",
    "salt shaker",
    "sandal",
    "sarong, a type of clothing",
    "saxophone, a type of musical instrument",
    "scabbard",
    "weighing scale",
    "school bus, a type of vehicle",
    "schooner",
    "scoreboard",
    "CRT monitor",
    "screw",
    "screwdriver",
    "seat belt",
    "sewing machine",
    "shield",
    "shoe store, a type of building",
    "shoji screen / room divider",
    "shopping basket",
    "shopping cart",
    "shovel",
    "shower cap, a type of hat",
    "shower curtain",
    "ski",
    "balaclava ski mask",
    "sleeping bag",
    "slide rule",
    "sliding door",
    "slot machine",
    "snorkel",
    "snowmobile, a type of vehicle",
    "snowplow, a part of a vehicle",
    "soap dispenser",
    "soccer ball, a type of ball",
    "sock, a type of clothing worn on the foot",
    "solar thermal collector",
    "sombrero, a type of hat",
    "soup bowl",
    "keyboard space bar",
    "space heater, a type of appliance",
    "space shuttle, a type of airplane and spacecraft",
    "spatula",
    "motorboat, a type of boat",
    "spider web",
    "spindle",
    "sports car, a type of vehicle",
    "spotlight",
    "stage, a feature of a building",
    "steam locomotive, a type of train",
    "through arch bridge, a type of bridge",
    "steel drum, a type of musical instrument",
    "stethoscope",
    "scarf, a piece of clothing worn around the nect",
    "stone wall, a feature of buildings",
    "stopwatch",
    "stove, a type of kitchen appliance",
    "strainer",
    "tram, a type of vehicle",
    "stretcher",
    "couch, a type of furniture",
    "stupa",
    "submarine, a type of underwater boat",
    "suit, a type of clothing",
    "sundial",
    "sunglasses",
    "sunglasses",
    "sunscreen",
    "suspension bridge, a type of bridge",
    "mop",
    "sweatshirt, a type of clothing",
    "swim trunks / shorts, a type of clothing",
    "swing",
    "electrical switch",
    "syringe",
    "table lamp",
    "tank, a type of vehicle",
    "tape player",
    "teapot",
    "teddy bear",
    "television",
    "tennis ball, a type of ball",
    "thatched roof, a type of roofing",
    "front curtain",
    "thimble",
    "threshing machine, a type of vehicle",
    "throne",
    "tile roof, a type of roofing",
    "toaster, a type of kitchen appliance",
    "tobacco shop, a type of building",
    "toilet seat",
    "torch",
    "totem pole",
    "tow truck, a type of vehicle",
    "toy store, a type of building",
    "tractor, a type of vehicle",
    "semi-trailer truck, a type of vehicle",
    "tray",
    "trench coat, a type of coat",
    "tricycle",
    "trimaran, a type of boat",
    "tripod",
    "triumphal arch, a feature of a building",
    "trolleybus, a type of vehicle",
    "trombone, a type of musical instrument",
    "hot tub",
    "turnstile",
    "typewriter keyboard",
    "umbrella",
    "unicycle",
    "upright piano, a type of musical instrument",
    "vacuum cleaner, a type of appliance",
    "vase",
    "vaulted or arched ceiling, a feature of a building",
    "velvet fabric",
    "vending machine",
    "vestment",
    "viaduct, a feature of a building",
    "violin",
    "volleyball, a type of ball",
    "waffle iron",
    "wall clock, for telling the time",
    "wallet",
    "wardrobe, a type of furniture",
    "military aircraft, a type of airplane",
    "sink",
    "washing machine, a type of appliance",
    "water bottle",
    "water jug",
    "water tower, a type of building",
    "whiskey jug",
    "whistle",
    "hair wig",
    "window screen",
    "window shade",
    "Windsor tie, a type of necktie",
    "wine bottle",
    "airplane wing",
    "wok",
    "wooden spoon",
    "wool",
    "split-rail fence",
    "shipwreck",
    "sailboat, a type of boat",
    "yurt, a type of building",
    "website",
    "comic book",
    "crossword",
    "traffic or street sign",
    "traffic light",
    "dust jacket",
    "menu",
    "plate",
    "guacamole, a type of food",
    "consomme, a type of food",
    "hot pot, a type of food",
    "trifle, a type of food",
    "ice cream, a type of food",
    "popsicle, a type of food",
    "baguette, a type of bread",
    "bagel, a type of bread",
    "pretzel, a type of bread",
    "cheeseburger, a type of food",
    "hot dog, a type of food",
    "mashed potatoes, a type of food",
    "cabbage, a type of vegetable",
    "broccoli, a type of vegetable",
    "cauliflower, a type of vegetable",
    "zucchini, a type of vegetable",
    "spaghetti squash, a type of vegetable",
    "acorn squash, a type of vegetable",
    "butternut squash, a type of vegetable",
    "cucumber, a type of vegetable",
    "artichoke, a type of vegetable",
    "bell pepper",
    "cardoon",
    "mushroom",
    "Granny Smith apple, a type of fruit",
    "strawberry, a type of fruit",
    "orange, a type of fruit",
    "lemon, a type of fruit",
    "fig, a type of fruit",
    "pineapple, a type of fruit",
    "banana, a type of fruit",
    "jackfruit, a type of fruit",
    "cherimoya (custard apple), a type of fruit",
    "pomegranate, a type of fruit",
    "hay",
    "carbonara, a type of food",
    "chocolate syrup, a type of food",
    "dough, a type of food",
    "meatloaf, a type of food",
    "pizza, a type of food",
    "pot pie, a type of food",
    "burrito, a type of food",
    "red wine, a type of drink",
    "espresso, a type of drink",
    "tea cup",
    "eggnog, a type of drink",
    "mountain",
    "bubble",
    "cliff",
    "coral reef",
    "geyser",
    "lakeshore",
    "promontory",
    "sandbar",
    "beach",
    "valley",
    "volcano",
    "baseball player",
    "bridegroom",
    "scuba diver",
    "rapeseed",
    "daisy",
    "yellow lady's slipper",
    "corn",
    "acorn",
    "rose hip",
    "horse chestnut seed",
    "coral fungus",
    "agaric",
    "gyromitra",
    "stinkhorn mushroom",
    "earth star fungus",
    "hen of the woods mushroom",
    "bolete",
    "corn cob",
    "toilet paper",
]


openai_imagenet_template = [
    lambda c: f'a photo of a {c}.',
    lambda c: f'a photo of the {c}.',
    lambda c: f'a photo of {c}.',
    lambda c: f'a cropped photo of the {c}.',
    lambda c: f'a bright photo of a {c}.',
    lambda c: f'a photo of the cool {c}.',
    lambda c: f'a close-up photo of a {c}.',
    lambda c: f'a close-up photo of the {c}.',
    lambda c: f'a depiction of the {c}.',
    lambda c: f'a depiction of a {c}.',
    lambda c: f'an example of the {c}.',
    lambda c: f'an example of a {c}.',
    lambda c: f'a good photo of the {c}.',
    lambda c: f'a photograph of {c}.',
    lambda c: f'a photograph of a {c}.',
    lambda c: f'a photograph of the {c}.',
    lambda c: f'an image of {c}.',
    lambda c: f'an image of the {c}.',
    lambda c: f'an image of a {c}.',
    lambda c: f'an image illustrating {c}.',
    lambda c: f'an image illustrating the {c}.',
    lambda c: f'an image illustrating a {c}.',
    lambda c: f'an image depicting {c}.',
    lambda c: f'an image depicting the {c}.',
    lambda c: f'an image depicting a {c}.',
    lambda c: f'an image resembling {c}.',
    lambda c: f'an image resembling the {c}.',
    lambda c: f'an image resembling a {c}.',
    lambda c: f'an image displaying {c}.',
    lambda c: f'an image displaying the {c}.',
    lambda c: f'an image displaying a {c}.',
    lambda c: f'a portrayal of {c}.',
    lambda c: f'a portrayal of the {c}.',
    lambda c: f'a portrayal of a {c}.',
    lambda c: f'a rendition of a {c}.',
    lambda c: f'a rendition of the {c}.',
    lambda c: f'a rendition of {c}.',
    lambda c: f'a photo of a nice {c}.',
    lambda c: f'a photo of the nice {c}.',
    lambda c: f'a photo of the large {c}.',
    lambda c: f'a photo of a cool {c}.',
    lambda c: f'a photo of a small {c}.',
]
